gruppe-adler/grad_civs

cfgFunctions.hpp, functions/init/fn_initModule.sqf, functions/sm_activities/fn_sm_activities.sqf, functions/sm_activities/fn_sm_activities_state_panic_enter.sqf, functions/sm_business/fn_sm_business.sqf, functions/sm_business/fn_sm_business_state_housework_enter.sqf, functions/sm_business/fn_sm_business_state_housework_exit.sqf, functions/sm_business/fn_sm_business_state_meetNeighbor_enter.sqf, functions/sm_lifecycle/fn_sm_lifecycle_state_spawn_enter.sqf, functions/spawn/fn_serverLoop.sqf
* add `switchMove ""` on household exit
* execute all `switchMove globally` [just like ZEN is doing](https://github.com/zen-mod/ZEN/blob/906f462b8c3f7868444e5731cfe6546ce8451abb/addons/modules/functions/fnc_moduleAmbientAnimEnd.sqf#L45)
* take care to remove non-local civs from grad-civs control
* log non-local and NULL civs
=> Unstuck anims

README.md, component.hpp, functions/common/fn_getGlobalCivs.sqf, functions/init/fn_initConfig.sqf, functions/sm_business/fn_sm_business_trans_housework_meetNeighbor_condition.sqf, functions/spawn/fn_serverLoop.sqf, functions/spawn/fn_spawnCivilian.sqf
* replace GRAD_CIVS_CIVCLASS definition with civClass config value
* add to README
* sort config values in README (yay)
=> config values "civClass" replaces `#define GRAD_CIVS_CIVCLASS`

README.md, cfgFunctions.hpp, docs/states.gv, functions/common/fn_formatNowPlusSeconds.sqf, functions/common/fn_nowPlusSeconds.sqf, functions/sm_activities/fn_sm_activities.sqf, functions/sm_activities/fn_sm_activities_state_asOrdered_enter.sqf, functions/sm_activities/fn_sm_activities_state_asOrdered_loop.sqf, functions/sm_activities/fn_sm_activities_trans_asOrdered_business_condition.sqf, functions/sm_business/fn_sm_business_trans_rally_housework_condition.sqf
* add custom events `GRAD_civs_customActivity_start`  and `GRAD_civs_customActivity_end` to enable missionmakers to temporarily insert custom behavior:
```markdown
To let civilians break from their usual activity and do something else, you can use events:
This will make the civilian available to be given custom commands without interference from grad-civs:
`["GRAD_civs_customActivity_start", [_civ], _civ] call CBA_fnc_targetEvent;`
To end the custom activity and make the civ resume their normal stuff, fire another event:
`["GRAD_civs_customActivity_end", [_civ], _civ] call CBA_fnc_targetEvent;`
**NOTE**: this whole thing will *NOT* work while they are panicking.
```
* adjust cooldown times for "send away", "get down", "honked at" behavior
=> Custom behavior events

functions/common/fn_findBuildings.sqf, functions/common/fn_isInHouse.sqf, functions/common/fn_isInPopulatedZone.sqf, functions/init/fn_initConfig.sqf, functions/sm_lifecycle/fn_sm_lifecycle_trans_life_despawn_condition.sqf, functions/spawn/fn_addResident.sqf, functions/spawn/fn_findSpawnPosition.sqf, functions/spawn/fn_findUnclaimedHouse.sqf
* optimize finding house ("find first"  instead of "filter all then select random")
* config bugfix : setting group size as single value was off by one (1 led to 0-size groups, welp)
* some of macro usage
* start filter for unsuitable gm houses (like... fences -.-)
~~TODO: test with vehicles / high distances~~
löppt.
on a test on Weferlingen with 
`spawnDistancesInVehicles[] = {1500,2500};` spawning a group of abt 6 civs took 36ms with an according frametime jump. (hence: do use HC!) . waypoint planning was faster.
=> optimization & bugfixes

cfgFunctions.hpp, functions/api/fn_addExclusionZone.sqf, functions/api/fn_addPopulationZone.sqf, functions/init/fn_initPlayer.sqf, functions/player/fn_setupZeusModules.sqf, functions/player/fn_showCivHint.sqf, functions/spawn/fn_createInfoChannel.sqf
depends on ZEN which lets you add area markers as Zeus.
as Zeus
* create area marker using ZEN module (look in "Misc")
* select the GRAD_CIVS "ADD EXCLUSION ZONE" module and click somewher within the area you just created
* DONE! no new civs will spawn in that area or create waypoints there
note: we cannot click *on* the area marker, b/c ZEN has registered the click handler for opening a dialog
_note: as we're storing a reference to the area itself, you can edit the area using ZEN and the exclusion zone will change with it._
=> add exclusion zone via zeus module

functions/player/fn_checkWeaponOnCivilianPointer.sqf
As !weaponLowered doers *not* mean "weaponRaised", check player animationState before causing civilian to surrender.
fixes #58
=> use animation for checking raised weapon

functions/behaviour/fn_taskPatrolFindWaypoint.sqf, functions/behaviour/fn_taskPatrolFindWaypoints.spec.sqf
if there were no exclusion zones, patrols would not get waypoints (weirdly it *did* work sometimes :tinfoil: )
=> Fix patrol waypoints

addons/cars/functions/fnc_spawnCarAndCrew.sqf, addons/common/XEH_PREP.hpp, addons/common/functions/fnc_parseCsv.spec.sqf, addons/common/functions/fnc_parseCsv.sqf, addons/legacy/functions/fnc_sm_lifecycle_state_spawn_enter.sqf, addons/loadout/functions/fnc_applyRandomConfigArrayValue.sqf, addons/patrol/XEH_postInit.sqf, addons/patrol/functions/fnc_addFootsy.sqf, addons/residents/XEH_postInit.sqf, addons/residents/functions/fnc_addResident.sqf, addons/transit/README.md, addons/transit/functions/fnc_addTransitRoute.sqf, addons/transit/functions/fnc_addTransitVehicle.sqf, addons/transit/functions/fnc_initConfig.sqf, addons/transit/functions/fnc_module_transitSource.sqf, addons/transit/functions/fnc_sm_business_trans_mountUp_transit_condition.sqf, addons/transit/functions/fnc_spawnSomething.sqf, addons/voyage/XEH_postInit.sqf, addons/voyage/functions/fnc_addCarCrew.sqf
* allow CSV-style config lists. these all are valid:
```
["a", "b"]
"a","b"
a,b
```
* fix vehicle classes config for transit - now its
`3den module > transit addon > cars addon`
* probably fix mountUp->transit condition
Here, cars started to move while units were disembarked (or disembarking?).
My guess: `crew` is more accurate than `vehicle`
* optimize mountUp->transit condition
=> fix transit vehicle config

addons/voyage/functions/fnc_sm_business_state_voyage_loop.sqf
...provided SQF execution does not suspend within a single statement.
By putting everything array selection into a single statement, the index should not be getting stale anymore between one line and the next.
=> fix #39 once and for all

README.md, addons/legacy/functions/fnc_serverLoop.sqf, addons/legacy/functions/fnc_sm_activities_state_surrendered_enter.sqf, addons/legacy/functions/fnc_sm_lifecycle_state_death_enter.sqf, addons/legacy/functions/fnc_sm_lifecycle_state_spawn_enter.sqf, addons/legacy/functions/fnc_sm_lifecycle_trans_life_despawn_condition.sqf, addons/legacy/functions/fnc_spawnPass.sqf, addons/patrol/functions/fnc_taskPatrol.sqf, addons/transit/functions/fnc_sm_lifecycle.sqf, addons/voyage/functions/fnc_initConfig.sqf, addons/voyage/functions/fnc_sm_business_state_voyage_enter.sqf, addons/voyage/functions/fnc_sm_business_state_voyage_loop.sqf
* do not run all the spawn & other loops while game is paused
* predictable despawn check every 10s for individual units
* remove old non-stackable events (all of them broken rn anyway)
* set `grad_civs_livedAs` on death so as to identify the body later even after group gets deleted
* fix ASR AI exclusion in the event of locality change
* fix distance despawn condition
* reduce log level of periodic tasks
* add optional config var for voyagers.: "maximum travel distance from spawn". defaults to max spawn distance from players. was fixed at 2500 before.
=> various bugfixes & clean ups

addons/cars/functions/fnc_spawnCarAndCrew.sqf, addons/interact/functions/fnc_addInteractEventHandlers.sqf, addons/interact/functions/fnc_checkWeaponOnCivilianPointer.sqf, addons/interact/functions/fnc_sm_activities_state_surrendered_enter.sqf, addons/interact/functions/fnc_sm_activities_state_surrendered_exit.sqf
the bug had two components, both of which are now fixed:
* passengers did not raise their hands if player did not immediately switch from targeting the vehicle to targeting the unit (a regression brought about in a major refactor some time ago)
* passengers kept their dismount orientation - thus often they could not see the pointing player, got unpointed because of that, and thus did not surrender
=> fix #92 (surrender after dismount)

.github/workflows/ci.yml
for unknown reasons, bisign in the hemtt for windows build behaves properly
=> fix #96 - build on windows

README.md, addons/activities/config.cpp, addons/interact/XEH_postInit.sqf, addons/interact/config.cpp, addons/interact/functions/fnc_sm_activities_state_surrendered_enter.sqf, addons/interact/functions/fnc_sm_activities_state_surrendered_exit.sqf, addons/mimikry/config.cpp, addons/mimikry/functions/fnc_showCivHint.sqf
some things do not work without ACE, but there you go....
fixes #140 
NOTE: there is no `#define WITH_ACE3_DEPENDENCY` anywhere, but I'm still using `#ifdef WITH_ACE3_DEPENDENCY` in configs to mark the ACE things that are  being used in the respective addon
=> remove hard ACE dependency

addons/activities/XEH_postInit.sqf, addons/cars/XEH_postInit.sqf, addons/common/XEH_postInit.sqf, addons/diagnostics/XEH_postInit.sqf, addons/gta/XEH_postInit.sqf, addons/interact/XEH_postInit.sqf, addons/lifecycle/XEH_postInit.sqf, addons/loadout/XEH_postInit.sqf, addons/main/XEH_postInit.sqf, addons/mimikry/XEH_postInit.sqf, addons/patrol/XEH_postInit.sqf, addons/residents/XEH_postInit.sqf, addons/transit/XEH_postInit.sqf, addons/voyage/XEH_postInit.sqf, addons/zeus/XEH_postInit.sqf
Prevents race conditions whereby the `grad_civs_main_enabled` flag could be initialized after the scripts are executed.
Tested:
* Locally to ensure addons are still invoked
* Dedicated server with headless client
Dedicated server test scenarios:
1. Starting Headless Client 5 minutes after server start.
2. Starting headless client with dedicated server, prior to mission start
In both scenarios, where the dedicated server and headless client both owned the civilian objects, civilians did spawn successfully and there were no issues with evaluating the value of `grad_civs_main_enabled`.
I haven't tested bug #125 but this change may also resolve that problem.
=> Run postInit when CBA_SettingsInitialized has been triggered

addons/cars/README.md, addons/cars/functions/fnc_spawnVehicle.sqf
Resolves #163 
Raised as a draft PR since I wasn't sure whether you'd prefer to keep the event logic in a state machine similar to the `grad_civs_civKilled` event. Feedback and suggestions are welcome.
=> Add Killed Event Handler to vehicles

addons/common/README.md, addons/common/XEH_PREP.hpp, addons/common/functions/fnc_removeExclusionZone.sqf, addons/lifecycle/README.md, addons/lifecycle/XEH_PREP.hpp, addons/lifecycle/functions/fnc_setCivilians.sqf
Adds a function, similar to `setVehicles`, that allows you to override the civilian classnames without directly manipulating the global variable.
This also updates the documentation of `grad_civs_common_fnc_addPopulationZone` to provide an alternative syntax for adding exclusion zones programmatically.
=> Add ability to override civClasses

addons/cars/functions/fnc_setVehicles.sqf, addons/lifecycle/functions/fnc_setCivilians.sqf, addons/residents/functions/fnc_sm_business_state_housework_enter.sqf
Fixes the housework_enter state whereby the `random` evaluation would fail due to the if statement not being wrapped. Also changed to use the alternative syntax for if-else values.
Updated the `setCivilians` and `setVehicles` functions to update CBA at a server level while storing the value. I've found that using `"mission"` doesn't broadcast the value to headless clients that are JIP.
=> Post-release bugfixes

addons/cars/functions/fnc_initConfig.sqf, addons/diagnostics/functions/fnc_showInfoLine.sqf, addons/transit/functions/fnc_sm_business_state_transit_loop.sqf, addons/voyage/functions/fnc_sm_business_state_voyage_loop.sqf
with the aim of reducing accidents,
~~this changes vehicles from driving in "limited" speed mode (which varies depending on max vehicle speed) to using a fixed absolute speed limit for orientation.~~
* set a globally defined speed limit on vehicles using `limitSpeed` 
* config var `grad_civs_cars_globalSpeedLimit`
* defaults to 50 km/h
* set to -1 to disable
* changes to speed limit will take immediate effect
* NOTE: cannot use `forceSpeed` as vehicles would be forbidden from braking for tight turns
* fixes #169 (further ideas to improve that behaviour should be put into separate tickets)
=> add global speed limit

addons/cars/README.md, addons/cars/XEH_PREP.hpp, addons/cars/XEH_postInit.sqf, addons/cars/functions/fnc_determineSpeedLimits.sqf, addons/cars/functions/fnc_determineTownLocations.sqf, addons/cars/functions/fnc_initConfig.sqf, addons/cars/functions/fnc_pfh_speedLimit.sqf, addons/cars/functions/fnc_spawnVehicle.sqf, addons/diagnostics/README.md, addons/diagnostics/XEH_PREP.hpp, addons/diagnostics/functions/fnc_drawSpeedLimitsOnMap.sqf, addons/diagnostics/functions/fnc_initConfig.sqf, addons/diagnostics/functions/fnc_showInfoLine.sqf, addons/diagnostics/functions/fnc_showSpeedLimitsOnMap.sqf, addons/transit/functions/fnc_sm_business_state_transit_loop.sqf, addons/voyage/functions/fnc_sm_business_state_voyage_loop.sqf
extending the functionality of #170  : add another speed limit option for towns.
it's a bit rough, as it uses location data (locations are circles, and cities are not necessarily circlish), but it works nicely as a first approximation.
default speed limit within towns is 30km/h
fallout from this change includes:
* an array of local civilian vehicles
* local speed limit indicator in the debug "show info line: speed" display
* add diagnostics option to show speed limits on map
* a variable on the vehicles denoting their current speed limit
* for scripting : a global var containing custom speed limits (gets read contonuously). speed limits are applied after town speed limits in the order they appear in this GVAR.
* speed limits are now set from the cars addon, which nicely keeps that whole …
=> Local speed limit

addons/lifecycle/XEH_preInit.sqf, addons/lifecycle/functions/fnc_localSpawnPass.sqf, addons/lifecycle/functions/fnc_sm_lifecycle_trans_life_despawn_condition.sqf
Only prints the abstain / pass messages the first time to avoid RPT spam
This is very significant for servers with `persistent = 1`
=> Lifecycle: Reduce RPT Spam
